// src/components/organisms/About.svelte
<script>
	import RichPresence from '../molecules/RichPresence.svelte';
	import Tooltip from '../atoms/Tooltip.svelte';

	// i didnt write this idk
	let getAge = () => {
		let birthDate = new Date('2003/03/12');
		const ageMs = Date.now() - birthDate.getTime();
		const preciseAge = (ageMs / 31536000000).toFixed(10);
		return preciseAge;
	};

	let age = getAge();
	setInterval(() => {
		age = getAge();
	}, 1000);
</script>

<section id="about" class="wrapper about-section">
	<div class="section-header">
		<h2>About Me</h2>
		<p class="section-description">
			Get to know me better and see what I'm currently up to
		</p>
	</div>
	
	<div class="about-content card">
		<div class="discord-section">
			<RichPresence />
		</div>
		<div class="text">
			<div class="bio-content">
				<div class="bio-header">
					<div class="avatar-placeholder">
						<span class="avatar-icon">👨‍💻</span>
					</div>
					<div class="bio-info">
						<h3>Alex (Suman)</h3>
						<p class="bio-subtitle">Android Developer & Open Source Contributor</p>
					</div>
				</div>
				
				<div class="bio-text">
					<p>
						Hey there! I'm Suman, but people know me as Alex on the internet. :) I'm a <Tooltip tip={age}
							><span class="highlight">{Math.floor(Number(age))}</span></Tooltip
						>
						year-old native Android developer from India. I started programming as a hobby, but after
						<span class="highlight">2022</span>, I began taking it seriously. Over time, I've developed a strong passion for
						programming. I enjoy contributing to <Tooltip tip="🤓">
							<a href="https://github.com/alex5402" target="_blank" rel="noreferrer"
								><span class="highlight">open-source</span></a
							></Tooltip
						>
						Android projects, such as <Tooltip tip="KernelSU">
							<a href="https://github.com/tiann/KernelSU" target="_blank" rel="noreferrer"
								><span class="highlight">KernelSU</span></a
							></Tooltip
						>.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<style lang="scss">
	@use '../../styles/mixins.scss' as *;

	.about-section {
		margin: 6rem auto;
		animation: fadeInUp 1s var(--bezier-two);
		max-width: 1600px;
		padding: 0 3rem;

		@media (max-width: 1400px) {
			max-width: 1400px;
			padding: 0 2rem;
		}

		@media (max-width: 768px) {
			padding: 0 1rem;
		}
	}

	.section-header {
		text-align: center;
		margin-bottom: 4rem;
		animation: fadeInUp 1s var(--bezier-two) 0.2s both;
		max-width: 1000px;
		margin-left: auto;
		margin-right: auto;

		@media (max-width: 1400px) {
			max-width: 800px;
		}

		@media (max-width: 868px) {
			text-align: center;
			margin-bottom: 3rem;
			max-width: 100%;
		}
	}

	.section-description {
		font-size: 1.1rem;
		color: var(--text-secondary);
		max-width: 600px;
		margin: 1.5rem auto 0 auto;
		line-height: 1.6;

		@media (max-width: 868px) {
			margin: 1.5rem auto 0 auto;
		}
	}

	.about-content {
		display: grid;
		grid-template-columns: 0.8fr 1.2fr;
		gap: 5rem;
		align-items: start;
		max-width: 1400px;
		margin: 0 auto;

		@media (max-width: 1400px) {
			max-width: 1200px;
			gap: 4rem;
		}

		@media (max-width: 1200px) {
			grid-template-columns: 1fr;
			gap: 3rem;
			max-width: 900px;
		}

		@media (max-width: 768px) {
			gap: 2.5rem;
			max-width: 100%;
		}
	}

	.discord-section {
		display: flex;
		flex-direction: column;
		gap: 3rem;
	}

	.text {
		position: relative;
		line-height: 1.75rem;
	}

	.bio-content {
		animation: fadeInUp 1s var(--bezier-two) 0.4s both;
	}

	.bio-header {
		display: flex;
		align-items: center;
		gap: 2rem;
		margin-bottom: 2.5rem;
		padding: 2rem;
		background: var(--gradient-surface);
		border: 1px solid var(--border);
		border-radius: 16px;
		box-shadow: var(--shadow-sm);
	}

	.avatar-placeholder {
		width: 90px;
		height: 90px;
		border-radius: 50%;
		background: var(--gradient-primary);
		border: 3px solid var(--accent);
		display: flex;
		align-items: center;
		justify-content: center;
		box-shadow: var(--shadow-lg);
		position: relative;
		
		&::before {
			content: '';
			position: absolute;
			top: -2px;
			left: -2px;
			right: -2px;
			bottom: -2px;
			background: var(--gradient-primary);
			border-radius: 50%;
			z-index: -1;
			opacity: 0.3;
		}
		
		.avatar-icon {
			font-size: 2.8rem;
			filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.2));
		}
	}

	.bio-info h3 {
		margin: 0 0 0.75rem 0;
		font-size: 2rem;
		font-weight: 700;
		background: var(--gradient-text);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
		line-height: 1.2;
	}

	.bio-subtitle {
		margin: 0;
		font-size: 1.1rem;
		color: var(--text-secondary);
		font-weight: 500;
		opacity: 0.9;
	}

	.bio-text {
		line-height: 1.8;
	}

	.highlight {
		font-weight: 600;
		font-family: var(--font-two);
		font-size: 0.9rem;
		background: var(--gradient-surface);
		border: 1px solid var(--border);
		border-radius: 8px;
		color: var(--accent);
		padding: 0.3rem 0.6rem;
		width: fit-content;
		display: inline-block;
		transition: all var(--transition-normal);
		
		&:hover {
			transform: translateY(-1px);
			box-shadow: var(--shadow-sm);
		}
	}

	a {
		text-decoration: none;
		color: inherit;
	}

	.text::before {
		@include outlineText(
			$content: 'alex5402',
			$translateX: 97%,
			$translateY: -5%,
			$fontSize: 300px,
			$opacity: 0.22
		);
	}

	@media (max-width: 868px) {
		.about-content {
			grid-template-columns: 1fr;
			gap: 2.5rem;
		}

		.discord-section {
			gap: 2rem;
		}

		.bio-header {
			flex-direction: column;
			text-align: center;
			gap: 1.5rem;
			padding: 1.5rem;
		}

		.avatar-placeholder {
			width: 70px;
			height: 70px;
			
			.avatar-icon {
				font-size: 2.2rem;
			}
		}

		.bio-info h3 {
			font-size: 1.6rem;
		}

		.bio-subtitle {
			font-size: 1rem;
		}
	}

	@media (max-width: 480px) {
		.bio-header {
			padding: 1rem;
			gap: 1rem;
		}

		.avatar-placeholder {
			width: 60px;
			height: 60px;
			
			.avatar-icon {
				font-size: 2rem;
			}
		}

		.bio-info h3 {
			font-size: 1.4rem;
		}
	}
</style>

// src/components/About.tsx
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import alexPortrait from "@/assets/alex-portrait.png";
import { useAge } from "@/hooks/use-age";

const About = () => {
  // Set your birthdate here - adjust this to your actual birthdate
  const birthDate = new Date('2003-03-12'); // Example: January 15, 2002
  const age = useAge(birthDate);

  const stats = [
    { label: "Total Repositories", value: "225", suffix: "+100 public" },
    { label: "Stars Earned", value: "453", suffix: "total" },
    { label: "Forks", value: "261", suffix: "total" },
    { label: "Followers", value: "101", suffix: "total" },
  ];

  const skills = [
    { name: "Android Development", level: 95 },
    { name: "Kotlin", level: 90 },
    { name: "Java", level: 85 },
    { name: "Open Source", level: 88 },
    { name: "Mobile UI/UX", level: 82 },
    { name: "Git & GitHub", level: 92 },
  ];

  return (
    <section className="py-20 px-4 relative" id="about">
      <div className="container mx-auto relative z-10">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            <span className="text-gradient">About Me</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Get to know me better and see what I'm currently up to
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12 items-start">
          {/* Personal Info Card with enhanced animations */}
          <Card className="glass p-8 space-y-6 tilt-card group hover:shadow-2xl transition-all duration-500">
            <div className="flex items-start gap-6">
              <div className="relative">
                <img 
                  src={alexPortrait}
                  alt="Alex (Suman) - Android Developer"
                  className="w-24 h-24 rounded-2xl object-cover ring-2 ring-primary/20 group-hover:ring-primary/40 transition-all duration-300 hover:scale-110"
                />
                <div className="absolute -bottom-2 -right-2 w-8 h-8 bg-success rounded-full border-4 border-background flex items-center justify-center pulse-ring">
                  <div className="w-3 h-3 bg-white rounded-full animate-pulse" />
                </div>
              </div>
              
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2 text-gradient">Alex (Suman)</h3>
                <p className="text-accent font-medium mb-2 hover:text-primary transition-colors cursor-default">Android Developer & Open Source Contributor</p>
                <div className="mb-4 inline-flex items-center gap-2 px-3 py-1 rounded-full bg-success/10 border border-success/20">
                  <div className="w-2 h-2 bg-success rounded-full animate-pulse" />
                  <span className="text-sm text-success font-medium">💭 Just chilling</span>
                </div>
                
                <p className="text-foreground/80 leading-relaxed hover:text-foreground transition-colors duration-300">
                  Hey there! I'm Suman, but people know me as Alex on the internet. :) I'm a{" "}
                  <span className="text-primary font-semibold hover:text-gradient-reverse transition-all duration-300 cursor-default group relative">
                    {age.years}-year-old
                    <div className="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-primary/90 text-primary-foreground text-xs px-2 py-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap z-10">
                      {age.totalYears.toFixed(10)} years old
                    </div>
                  </span> native Android developer from India. 
                  I started programming as a hobby, but after 2022, I began taking it seriously. 
                  Over time, I've developed a strong passion for programming.
                </p>
              </div>
            </div>

            <div className="space-y-4">
              <p className="text-foreground/80 hover:text-foreground transition-colors duration-300">
                I enjoy contributing to{" "}
                <a href="https://github.com/alex5402" className="text-accent hover:text-primary font-medium transition-all duration-300 hover:underline decoration-2 underline-offset-4">
                  🤓 open-source
                </a>{" "}
                Android projects, such as{" "}
                <a href="https://github.com/tiann/KernelSU" className="text-primary hover:text-accent font-medium transition-all duration-300 hover:underline decoration-2 underline-offset-4">
                  KernelSU
                </a>.
              </p>

              {/* Enhanced Skills Progress with stagger animation */}
              <div className="space-y-3 pt-4">
                <h4 className="font-semibold text-foreground flex items-center gap-2">
                  <span className="animate-bounce-gentle">🚀</span>
                  Technical Skills
                </h4>
                <div className="stagger-children space-y-3">
                  {skills.map((skill, index) => (
                    <div key={skill.name} className="space-y-1 group/skill">
                      <div className="flex justify-between text-sm">
                        <span className="text-foreground/80 group-hover/skill:text-foreground transition-colors">{skill.name}</span>
                        <span className="text-primary font-medium group-hover/skill:text-accent transition-colors">{skill.level}%</span>
                      </div>
                      <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                        <div 
                          className="bg-gradient-to-r from-primary to-accent rounded-full h-2 transition-all duration-2000 ease-out group-hover/skill:from-accent group-hover/skill:to-primary"
                          style={{ 
                            width: `${skill.level}%`,
                            animationDelay: `${index * 0.2}s`
                          }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </Card>

          {/* Enhanced GitHub Analytics */}
          <div className="space-y-6">
            <Card className="glass p-6 tilt-card group hover:shadow-xl transition-all duration-500">
              <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                <span className="animate-spin-slow">📦</span> GitHub Analytics
                <div className="ml-auto flex items-center gap-1 px-2 py-1 rounded-full bg-primary/10 border border-primary/20">
                  <div className="w-2 h-2 bg-primary rounded-full animate-pulse" />
                  <span className="text-xs text-primary font-medium">Real-time</span>
                </div>
              </h3>
              
              <div className="grid grid-cols-2 gap-4 stagger-children">
                {stats.map((stat, index) => (
                  <div key={stat.label} className="text-center p-4 rounded-lg bg-muted/20 border border-border/50 hover:bg-primary/5 hover:border-primary/30 transition-all duration-300 group/stat tilt-card">
                    <div className="text-2xl font-bold text-primary mb-1 group-hover/stat:text-accent transition-colors group-hover/stat:scale-110 transform duration-300">{stat.value}</div>
                    <div className="text-sm text-muted-foreground mb-1 group-hover/stat:text-foreground transition-colors">{stat.label}</div>
                    <div className="text-xs text-accent group-hover/stat:text-primary transition-colors">{stat.suffix}</div>
                  </div>
                ))}
              </div>
            </Card>

            {/* Enhanced Activity Card */}
            <Card className="glass p-6 tilt-card group hover:shadow-xl transition-all duration-500">
              <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                <span className="animate-pulse-glow">⚡</span> Current Activity
              </h3>
              <div className="space-y-3 stagger-children">
                <div className="flex items-center gap-3 p-3 rounded-lg bg-primary/10 border border-primary/20 hover:bg-primary/20 hover:scale-105 transition-all duration-300 group/activity">
                  <div className="w-3 h-3 bg-primary rounded-full animate-pulse" />
                  <span className="text-sm group-hover/activity:text-primary transition-colors">Working on Android projects</span>
                </div>
                <div className="flex items-center gap-3 p-3 rounded-lg bg-accent/10 border border-accent/20 hover:bg-accent/20 hover:scale-105 transition-all duration-300 group/activity">
                  <div className="w-3 h-3 bg-accent rounded-full animate-pulse" />
                  <span className="text-sm group-hover/activity:text-accent transition-colors">Contributing to KernelSU</span>
                </div>
                <div className="flex items-center gap-3 p-3 rounded-lg bg-muted/20 border border-border/50 hover:bg-muted/30 hover:scale-105 transition-all duration-300 group/activity">
                  <div className="w-3 h-3 bg-muted-foreground rounded-full animate-bounce-gentle" />
                  <span className="text-sm group-hover/activity:text-foreground transition-colors">Learning new technologies</span>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;
