// src/components/Hero.tsx
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Github, Mail, GamepadIcon, DollarSign, ExternalLink } from "lucide-react";
import heroImage from "@/assets/hero-bg.jpg";
import ParticleBackground from "./ParticleBackground";

const Hero = () => {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
    
    const handleMouseMove = (e: MouseEvent) => {
      setMousePosition({
        x: (e.clientX / window.innerWidth) * 100,
        y: (e.clientY / window.innerHeight) * 100,
      });
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  const scrollToWork = () => {
    const workSection = document.getElementById('work');
    if (workSection) {
      workSection.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-animated">
      <ParticleBackground />
      
      {/* Dynamic Background Image with Parallax */}
      <div 
        className="absolute inset-0 bg-cover bg-center bg-no-repeat opacity-30 transition-transform duration-1000 ease-out"
        style={{ 
          backgroundImage: `url(${heroImage})`,
          transform: `translate(${mousePosition.x * 0.02}px, ${mousePosition.y * 0.02}px) scale(1.1)`
        }}
      />
      
      {/* Enhanced Animated Background Elements */}
      <div className="absolute inset-0">
        <div className="absolute top-20 left-10 w-64 h-64 bg-primary/20 rounded-full blur-3xl animate-float" />
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-accent/20 rounded-full blur-3xl animate-float-slow" />
        <div className="absolute top-1/2 left-1/4 w-32 h-32 bg-primary/10 rounded-full blur-2xl animate-bounce-gentle" />
        <div className="absolute bottom-1/3 left-10 w-48 h-48 bg-accent/15 rounded-full blur-2xl animate-pulse-glow" />
        
        {/* Rotating geometric shapes */}
        <div className="absolute top-1/4 right-1/4 w-16 h-16 border-2 border-primary/30 rotate-45 animate-spin-slow" />
        <div className="absolute bottom-1/4 left-1/3 w-12 h-12 border-2 border-accent/30 rounded-full animate-pulse" />
      </div>

      <div className="relative z-10 container mx-auto px-4 text-center">
        {/* Welcome Badge with enhanced animation */}
        <div className={`mb-8 transition-all duration-1000 ${isVisible ? 'reveal-up' : 'opacity-0 translate-y-12'}`}>
          <div className="inline-flex items-center gap-2 px-6 py-3 rounded-full glass border gradient-border group hover:scale-105 transition-all duration-300">
            <span className="text-2xl animate-wiggle">👋</span>
            <span className="text-sm text-muted-foreground group-hover:text-foreground transition-colors">Welcome to my portfolio</span>
          </div>
        </div>

        {/* Main Title with shimmer effect */}
        <h1 className={`text-6xl md:text-8xl font-bold mb-6 transition-all duration-1000 delay-200 ${isVisible ? 'reveal-up-delay' : 'opacity-0 translate-y-12'}`}>
          <span className="text-shimmer">ALEX</span>
        </h1>

        {/* Subtitle with typewriter effect */}
        <div className={`space-y-2 mb-8 max-w-2xl mx-auto transition-all duration-1000 delay-400 ${isVisible ? 'reveal-up-delay-2' : 'opacity-0 translate-y-12'}`}>
          <p className="text-xl md:text-2xl text-muted-foreground hover:text-gradient-reverse transition-all duration-500 cursor-default">
            I like to make things simple.
          </p>
          <p className="text-xl md:text-2xl text-muted-foreground hover:text-gradient transition-all duration-500 cursor-default">
            I love cats :)
          </p>
        </div>

        {/* Description with enhanced styling */}
        <p className={`text-lg text-muted-foreground max-w-3xl mx-auto mb-12 leading-relaxed transition-all duration-1000 delay-600 ${isVisible ? 'reveal-up-delay-3' : 'opacity-0 translate-y-12'}`}>
          <span className="text-gradient-reverse font-semibold">Android developer</span> passionate about creating elegant mobile solutions and building amazing user experiences.
          Currently crafting native Android apps and contributing to <span className="text-primary font-medium">open-source projects</span>.
        </p>

        {/* Enhanced CTA Section */}
        <div className={`space-y-8 transition-all duration-1000 delay-800 ${isVisible ? 'reveal-up-delay-3' : 'opacity-0 translate-y-12'}`}>
          <Button 
            size="lg" 
            className="glow-on-hover px-8 py-6 text-lg font-semibold rounded-xl group relative overflow-hidden pulse-ring"
            onClick={scrollToWork}
          >
            <span className="relative z-10 flex items-center gap-2">
              Discover my work 
              <span className="inline-block animate-bounce-gentle">↓</span>
            </span>
          </Button>

          {/* Enhanced Social Links with stagger animation */}
          <div className="stagger-children flex justify-center gap-4 flex-wrap">
            <Button variant="outline" size="lg" className="glass accent-glow group tilt-card magnetic">
              <Github className="w-5 h-5 mr-2 group-hover:text-accent transition-all duration-300 group-hover:rotate-12" />
              <span>Github</span>
              <span className="ml-1 animate-wiggle">🔥</span>
            </Button>
            <Button variant="outline" size="lg" className="glass accent-glow group tilt-card magnetic">
              <Mail className="w-5 h-5 mr-2 group-hover:text-accent transition-all duration-300 group-hover:rotate-12" />
              <span>Mail Me</span>
              <span className="ml-1 animate-pulse">💌</span>
            </Button>
            <Button variant="outline" size="lg" className="glass accent-glow group tilt-card magnetic" asChild>
              <a href="https://buymeacoffee.com/alex5402" target="_blank" rel="noopener noreferrer">
                <DollarSign className="w-5 h-5 mr-2 group-hover:text-yellow-500 transition-all duration-300 group-hover:scale-110" />
                <span>Support</span>
                <span className="ml-1 animate-wiggle">😍</span>
              </a>
            </Button>
          </div>
          
          {/* alex5402.me Button */}
          <div className="flex justify-center mt-4">
            <Button variant="outline" size="sm" className="glass glow-on-hover group/btn" asChild>
              <a 
                href="https://alex5402.me" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2"
              >
                <ExternalLink className="w-4 h-4 group-hover/btn:rotate-12 transition-transform duration-300" />
                <span>alex5402.me</span>
              </a>
            </Button>
          </div>
        </div>
      </div>

      {/* Enhanced Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce-gentle group cursor-pointer">
        <div className="w-6 h-10 border-2 border-muted-foreground rounded-full flex justify-center group-hover:border-primary transition-colors">
          <div className="w-1 h-3 bg-muted-foreground rounded-full mt-2 animate-pulse group-hover:bg-primary transition-colors" />
        </div>
        <div className="text-xs text-muted-foreground mt-2 opacity-70 group-hover:opacity-100 transition-opacity">scroll</div>
      </div>
    </section>
  );
};

export default Hero;

// src/components/organisms/Hero.svelte
<script>
	import HeroImage from '../../components/atoms/HeroImage.svelte';
	import Button from '../atoms/Button.svelte';
	import Socials from '../molecules/Socials.svelte';

	function handleClick() {
		const el = document.querySelector('#github-analytics');
		if (!el) return;
		el.scrollIntoView({ 
			behavior: 'smooth',
			block: 'start'
		});
	}
</script>

<section id="home" class="wrapper hero-section">
	<div class="hero-content">
		<div class="hero-text">
			<div class="hero-badge">
				<span class="badge-icon">👋</span>
				<span class="badge-text">Welcome to my portfolio</span>
			</div>
			<h1>ALEX</h1>
			<h4>I like to make things simple. <br />I love cats :).</h4>
			<p class="hero-description">
				Android developer passionate about creating elegant mobile solutions and building amazing user experiences. 
				Currently crafting native Android apps and contributing to open-source projects.
			</p>
			<div class="hero-actions">
				<Button side on:click={handleClick} on:keypress={handleClick} class="btn-primary">
					<span>Discover my work</span>
					<span class="arrow">↓</span>
				</Button>
				<div class="socials">
					<Socials />
				</div>
			</div>
		</div>
		<div class="hero-visual">
			<HeroImage />
		</div>
	</div>
	
	<!-- Floating elements for visual interest -->
	<div class="floating-elements">
		<div class="floating-dot dot-1"></div>
		<div class="floating-dot dot-2"></div>
		<div class="floating-dot dot-3"></div>
	</div>
</section>

<style lang="scss">
	@use '../../styles/mixins.scss' as *;

	.hero-section {
		scroll-margin-top: 20rem;
		margin-bottom: 5.75rem;
		margin-top: 7rem;
		position: relative;
		overflow: hidden;

		@media screen and (max-width: 868px) {
			margin-top: 4rem;
		}

		@media screen and (max-width: 768px) {
			margin-bottom: 2.75rem;
		}
	}

	.hero-content {
		display: grid;
		grid-template-columns: 1.2fr 0.8fr;
		gap: 5rem;
		align-items: center;
		position: relative;
		z-index: 2;

		@media screen and (max-width: 1200px) {
			grid-template-columns: 1fr 1fr;
			gap: 4rem;
		}

		@media screen and (max-width: 1024px) {
			gap: 3rem;
		}

		@media screen and (max-width: 768px) {
			grid-template-columns: 1fr;
			gap: 2.5rem;
			text-align: center;
		}
	}

	.hero-text {
		animation: fadeInUp 1s var(--bezier-two);
	}

	.hero-badge {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 1rem;
		background: var(--gradient-surface);
		border: 1px solid var(--border);
		border-radius: 50px;
		margin-bottom: 1.5rem;
		box-shadow: var(--shadow-sm);
		animation: fadeInUp 1s var(--bezier-two) 0.2s both;

		.badge-icon {
			font-size: 1.2rem;
		}

		.badge-text {
			font-size: 0.9rem;
			font-weight: 500;
			color: var(--text-secondary);
		}
	}

	.hero-description {
		margin: 1.5rem 0;
		font-size: 1.1rem;
		line-height: 1.7;
		color: var(--text-secondary);
		max-width: 500px;
		animation: fadeInUp 1s var(--bezier-two) 0.4s both;

		@media screen and (max-width: 768px) {
			max-width: none;
		}
	}

	.hero-actions {
		display: flex;
		align-items: center;
		gap: 2.5rem;
		margin-top: 2.5rem;
		animation: fadeInUp 1s var(--bezier-two) 0.6s both;

		@media screen and (max-width: 768px) {
			flex-direction: column;
			gap: 2rem;
		}
	}

	.socials {
		display: flex;
		align-items: center;
		gap: 1.5rem;
		padding: 0.5rem;
		background: var(--gradient-surface);
		border: 1px solid var(--border);
		border-radius: 12px;
		box-shadow: var(--shadow-sm);
	}

	.arrow {
		display: inline-block;
		transition: transform var(--transition-normal);
	}

	.btn-primary:hover .arrow {
		transform: translateY(3px);
	}

	.hero-visual {
		position: relative;
		animation: fadeInUp 1s var(--bezier-two) 0.3s both;

		@media screen and (max-width: 768px) {
			order: -1;
		}
	}

	.floating-elements {
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		pointer-events: none;
		z-index: 1;
	}

	.floating-dot {
		position: absolute;
		width: 8px;
		height: 8px;
		background: var(--accent);
		border-radius: 50%;
		opacity: 0.6;
		animation: float 6s ease-in-out infinite;

		&.dot-1 {
			top: 20%;
			left: 10%;
			animation-delay: 0s;
		}

		&.dot-2 {
			top: 60%;
			right: 15%;
			animation-delay: 2s;
		}

		&.dot-3 {
			bottom: 30%;
			left: 20%;
			animation-delay: 4s;
		}
	}

	h1::before {
		@include outlineText($content: '///', $translateX: -95%, $letterSpacing: -0.1em);
	}

	@media screen and (max-width: 1240px) {
		h1 {
			min-height: 0vw;
			font-size: clamp(4rem, 10vw, 6.25rem);
		}

		h4 {
			min-height: 0vw;
			font-size: clamp(1.4rem, 2.4vw, 1.5rem);
		}
	}

	@media screen and (max-width: 400px) {
		h4 br {
			content: '&#160;';
		}
	}
</style>
